CREATE TABLE content_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(32) NOT NULL UNIQUE,
    display_name VARCHAR(80) NOT NULL,
    content_type VARCHAR(20) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_category_content_type CHECK (content_type IN ('ARTICLE', 'ALBUM'))
);

CREATE TABLE topic (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    code VARCHAR(40) NOT NULL,
    display_name VARCHAR(80) NOT NULL,
    slug VARCHAR(80) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_topic_category FOREIGN KEY (category_id) REFERENCES content_category(id) ON DELETE RESTRICT,
    CONSTRAINT uq_topic_category_code UNIQUE (category_id, code),
    CONSTRAINT uq_topic_category_slug UNIQUE (category_id, slug),
    CONSTRAINT uq_topic_id_category UNIQUE (id, category_id)
);

CREATE TABLE media_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type VARCHAR(20) NOT NULL,
    storage_key VARCHAR(512),
    external_url VARCHAR(1024),
    original_name VARCHAR(255),
    content_type VARCHAR(100),
    size_bytes BIGINT CHECK (size_bytes IS NULL OR size_bytes >= 0),
    width INTEGER CHECK (width IS NULL OR width >= 0),
    height INTEGER CHECK (height IS NULL OR height >= 0),
    alt_text VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'READY',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_media_source CHECK (
        (source_type = 'LOCAL_STATIC' AND external_url IS NOT NULL AND storage_key IS NULL)
        OR (source_type = 'S3' AND storage_key IS NOT NULL)
    ),
    CONSTRAINT ck_media_status CHECK (status IN ('UPLOADING', 'UPLOADED', 'PROCESSING', 'READY', 'FAILED'))
);

CREATE TABLE article (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(160) NOT NULL UNIQUE,
    title VARCHAR(240) NOT NULL,
    excerpt TEXT NOT NULL,
    body_markdown TEXT NOT NULL,
    body_html TEXT NOT NULL,
    category_id BIGINT NOT NULL,
    topic_id BIGINT NOT NULL,
    cover_asset_id BIGINT,
    status VARCHAR(20) NOT NULL,
    published_at TIMESTAMPTZ,
    read_minutes INTEGER NOT NULL CHECK (read_minutes > 0),
    version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    archived_at TIMESTAMPTZ,
    CONSTRAINT fk_article_category FOREIGN KEY (category_id) REFERENCES content_category(id) ON DELETE RESTRICT,
    CONSTRAINT fk_article_topic_category FOREIGN KEY (topic_id, category_id) REFERENCES topic(id, category_id) ON DELETE RESTRICT,
    CONSTRAINT fk_article_cover FOREIGN KEY (cover_asset_id) REFERENCES media_asset(id) ON DELETE SET NULL,
    CONSTRAINT ck_article_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    CONSTRAINT ck_article_published_at CHECK (status <> 'PUBLISHED' OR published_at IS NOT NULL)
);

CREATE TABLE album (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(160) NOT NULL UNIQUE,
    title VARCHAR(240) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_album_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    CONSTRAINT ck_album_published_at CHECK (status <> 'PUBLISHED' OR published_at IS NOT NULL)
);

CREATE TABLE album_photo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_id BIGINT NOT NULL,
    media_asset_id BIGINT NOT NULL,
    topic_id BIGINT,
    title VARCHAR(240),
    location VARCHAR(160),
    shot_at DATE,
    caption TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
    CONSTRAINT fk_album_photo_album FOREIGN KEY (album_id) REFERENCES album(id) ON DELETE CASCADE,
    CONSTRAINT fk_album_photo_media FOREIGN KEY (media_asset_id) REFERENCES media_asset(id) ON DELETE RESTRICT,
    CONSTRAINT fk_album_photo_topic FOREIGN KEY (topic_id) REFERENCES topic(id) ON DELETE RESTRICT,
    CONSTRAINT uq_album_photo_order UNIQUE (album_id, sort_order)
);

CREATE TABLE site_profile (
    id SMALLINT PRIMARY KEY CHECK (id = 1),
    display_name VARCHAR(120) NOT NULL,
    bio TEXT NOT NULL,
    manifesto TEXT NOT NULL,
    email VARCHAR(255),
    now_watching_title VARCHAR(240),
    now_watching_detail VARCHAR(240),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE homepage_feature (
    id SMALLINT PRIMARY KEY CHECK (id = 1),
    article_id BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_homepage_feature_article FOREIGN KEY (article_id) REFERENCES article(id) ON DELETE SET NULL
);

CREATE INDEX idx_article_published ON article(status, published_at DESC, id DESC);
CREATE INDEX idx_article_taxonomy_published ON article(category_id, topic_id, status, published_at DESC, id DESC);
CREATE INDEX idx_album_published ON album(status, published_at DESC, id DESC);
CREATE INDEX idx_album_photo_order ON album_photo(album_id, topic_id, sort_order);
