DO $$
DECLARE
    fixed_id_constraint TEXT;
BEGIN
    SELECT conname
      INTO fixed_id_constraint
      FROM pg_constraint
     WHERE conrelid = 'homepage_feature'::regclass
       AND contype = 'c'
       AND pg_get_constraintdef(oid) LIKE '%id = 1%';

    IF fixed_id_constraint IS NOT NULL THEN
        EXECUTE format('ALTER TABLE homepage_feature DROP CONSTRAINT %I', fixed_id_constraint);
    END IF;
END $$;

DELETE FROM homepage_feature WHERE article_id IS NULL;

ALTER TABLE homepage_feature
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 2),
    ALTER COLUMN article_id SET NOT NULL,
    ADD COLUMN sort_order INTEGER NOT NULL DEFAULT 0,
    ADD CONSTRAINT ck_homepage_feature_sort_order CHECK (sort_order >= 0),
    ADD CONSTRAINT uq_homepage_feature_article UNIQUE (article_id),
    ADD CONSTRAINT uq_homepage_feature_sort_order UNIQUE (sort_order);
