CREATE TABLE guest_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_name VARCHAR(60) NOT NULL,
    contact VARCHAR(120),
    message_text VARCHAR(2000) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'UNREAD',
    version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMPTZ,
    archived_at TIMESTAMPTZ,
    CONSTRAINT ck_guest_message_status CHECK (status IN ('UNREAD', 'READ', 'ARCHIVED')),
    CONSTRAINT ck_guest_message_state_time CHECK (
        (status = 'UNREAD' AND read_at IS NULL AND archived_at IS NULL)
        OR (status = 'READ' AND read_at IS NOT NULL AND archived_at IS NULL)
        OR (status = 'ARCHIVED' AND archived_at IS NOT NULL)
    )
);

CREATE INDEX idx_guest_message_inbox
    ON guest_message(status, created_at DESC, id DESC);
